version: '3.4'

services:
  dotnetcoredocker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      #-Mac
      #- ~/.aspnet/https:/root/.aspnet/https:ro
      #- ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      #-Window
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro